services:
  db:
    image: postgres:15
    container_name: restore_skills_db
    env_file:
     - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: restore_skills_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - db

volumes:
  postgres_data:
